# Generated by Django 4.2.17 on 2025-02-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Chiến dịch',
                'verbose_name_plural': 'Danh sách chiến dịch',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('loan_account_number', models.CharField(max_length=50, unique=True)),
                ('loan_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('family_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('current_area', models.CharField(blank=True, max_length=100, null=True)),
                ('id_card', models.CharField(max_length=20, unique=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('total_overdue', models.IntegerField(default=0)),
                ('mob', models.IntegerField(default=0)),
                ('tenor', models.IntegerField(default=0)),
                ('assigned_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Danh sách khách hàng',
            },
        ),
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('additional_phone_1', models.CharField(blank=True, max_length=15, null=True)),
                ('additional_phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('call_status', models.CharField(blank=True, max_length=50, null=True)),
                ('call_outcome_sub', models.CharField(blank=True, max_length=255, null=True)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('last_action_time', models.DateTimeField(blank=True, null=True)),
                ('last_action_code', models.CharField(blank=True, max_length=50, null=True)),
                ('last_remark', models.TextField(blank=True, null=True)),
                ('reference_phone_1', models.CharField(blank=True, max_length=15, null=True)),
                ('reference_phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('call_count', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_data', to='telesalesv2.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_data', to='telesalesv2.customer')),
            ],
            options={
                'verbose_name': 'Chiến dịch data',
                'verbose_name_plural': 'Danh sách chiến dịch data',
            },
        ),
    ]
