# Generated by Django 4.2.17 on 2025-02-25 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("telesalesv2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telesalesv2",
            name="serial_number",
        ),
    ]
