# Generated by Django 4.2.17 on 2025-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telesalesv2", "0002_remove_telesalesv2_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telesalesv2",
            name="call_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("follow1", "Follow1"),
                    ("follow2", "Follow2"),
                    ("follow3", "Follow3"),
                ],
                max_length=50,
                verbose_name="Trạng thái gọi",
            ),
        ),
    ]
