version: "3.9"

services:

  cnx:
    container_name: cnx
    build: .
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - db 
    env_file:
      - .env 

  db:
      image: mysql:8
      container_name: mysql_db
      restart: always
      environment:
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      ports:
        - "3307:3306"
      volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data: