# Generated by Django 4.2.17 on 2025-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0001_init_campaign_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "product_info",
            },
        ),
    ]
