# Generated by Django 4.2.17 on 2025-02-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0001_init_campaign_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("permanent_address", models.CharField(max_length=500)),
                ("temporary_address", models.CharField(max_length=500)),
                ("region", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "address_info",
            },
        ),
        migrations.CreateModel(
            name="ProductInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("product", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "product_info",
            },
        ),
    ]
