# Generated by Django 4.2.17 on 2025-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0002_create_address_info_table_and_product_info_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("spouse_name", models.CharField(max_length=300)),
                ("contact_name_1", models.CharField(max_length=300)),
                ("contact_relationship_1", models.CharField(max_length=300)),
                ("contact_name_2", models.CharField(max_length=300)),
                ("contact_relationship_2", models.CharField(max_length=300)),
                ("family_book", models.CharField(max_length=300)),
                ("other_contact_name", models.CharField(max_length=300)),
                ("other_contact_name_2", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "phone_info",
            },
        ),
    ]
