# Generated by Django 4.2.17 on 2025-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0003_create_phone_info_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("pds", models.BooleanField()),
                ("final", models.BooleanField()),
                ("contacted_person", models.CharField(max_length=300)),
                ("action_code", models.CharField(max_length=300)),
                ("reason_code", models.CharField(max_length=300)),
                ("note", models.TextField(max_length=300)),
                ("payment_date", models.DateField()),
                ("payment_amount", models.IntegerField()),
            ],
            options={
                "db_table": "call_outcome",
            },
        ),
    ]
