# Generated by Django 4.2.17 on 2025-02-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "name_call_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_customers", models.IntegerField(blank=True, null=True)),
                ("create_by", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "call_source",
            },
        ),
    ]
