# Generated by Django 4.2.17 on 2025-02-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callsource", "0002_alter_callsource_options_callsource_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="callsource",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hotline", "Hotline"),
                    ("community", "Community"),
                    ("digital", "Digital"),
                    ("crm_age", "CRM Age"),
                    ("retention", "Retention"),
                    ("etc", "ETC"),
                    ("referral", "Referral"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
