# Generated by Django 4.2.17 on 2025-03-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callsource", "0003_callsource_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryCallSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("uploader", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("total_uploaded", models.IntegerField()),
                ("successful_uploads", models.IntegerField()),
                ("failed_uploads", models.IntegerField()),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Uploaded File"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_sources",
                        to="callsource.callsource",
                    ),
                ),
            ],
            options={
                "db_table": "history_call_source",
            },
        ),
    ]
