# Generated by Django 4.2.17 on 2025-02-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0002_delete_customerinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=50)),
                ("id_number", models.CharField(max_length=20, unique=True)),
                ("day_of_birth", models.DateField()),
                (
                    "family_relation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("agency", models.CharField(blank=True, max_length=255, null=True)),
                ("contract_number", models.CharField(max_length=100)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_province",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("group", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "customer_info",
            },
        ),
    ]
