# Generated by Django 4.2.17 on 2025-02-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_create_contact_info_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("first_paid_date", models.DateField()),
                ("account_number", models.CharField(max_length=100)),
                (
                    "largest_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("last_payment_date", models.DateField()),
                ("disbursement_date", models.DateField()),
                ("cif", models.CharField(max_length=100)),
                ("due_date_overdue", models.DateField()),
                ("next_due_date", models.DateField()),
                (
                    "next_due_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "future_prin_amt",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("remain_prin", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pos_bom", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "db_table": "payment_info",
            },
        ),
    ]
