# Generated by Django 4.2.17 on 2025-02-24 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_create_payment_info_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactInfo",
        ),
        migrations.DeleteModel(
            name="CustomerInfo",
        ),
        migrations.DeleteModel(
            name="PaymentInfo",
        ),
    ]
