import uuid
from django.db import models
from cnx_service.model import BaseModel


class ChienDichData(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_by = models.CharField(max_length=255, null=True, blank=True)
    created_by_name = models.CharField(max_length=255, null=True, blank=True)
    modified_by = models.CharField(max_length=255, null=True, blank=True)
    modified_by_name = models.CharField(max_length=255, null=True, blank=True)
    c_time_lastcall = models.TextField(null=True, blank=True)
    c_thoigian_goilai = models.TextField(null=True, blank=True)
    c_solan_call = models.TextField(null=True, blank=True)
    c_queue_status = models.TextField(null=True, blank=True)
    c_nguon = models.TextField(null=True, blank=True)
    c_fkcd = models.CharField(max_length=255, null=True, blank=True)
    c_agent_ans = models.TextField(null=True, blank=True)
    c_fkkh = models.CharField(max_length=255, null=True, blank=True)
    c_call_id = models.TextField(null=True, blank=True)
    c_solan_goi = models.TextField(null=True, blank=True)
    c_stt = models.CharField(max_length=255, null=True, blank=True)
    c_update_time = models.TextField(null=True, blank=True)
    c_subrow_desc_number = models.TextField(null=True, blank=True)
    c_call_status = models.TextField(null=True, blank=True)
    c_calloutcome = models.TextField(null=True, blank=True)
    c_calloutcome_sub = models.TextField(null=True, blank=True)
    c_phone = models.TextField(null=True, blank=True)
    c_trangthai = models.TextField(null=True, blank=True)
    c_fkduyet = models.TextField(null=True, blank=True)
    c_callstatus = models.TextField(null=True, blank=True)
    c_status = models.CharField(max_length=35, null=True, blank=True)
    c_datefinal = models.TextField(null=True, blank=True)
    c_note = models.TextField(null=True, blank=True)
    c_brtype = models.TextField(null=True, blank=True)
    c_city = models.TextField(null=True, blank=True)
    c_subject = models.TextField(null=True, blank=True)
    c_channel = models.TextField(null=True, blank=True)
    c_ward = models.TextField(null=True, blank=True)
    c_diachimoi = models.TextField(null=True, blank=True)
    c_brstatus = models.TextField(null=True, blank=True)
    c_brbrand = models.TextField(null=True, blank=True)
    c_brandswitchreason = models.TextField(null=True, blank=True)
    c_brprevbrand = models.TextField(null=True, blank=True)
    c_registrationdate = models.TextField(null=True, blank=True)
    c_dropoutreason = models.TextField(null=True, blank=True)
    c_mainaddressstreetline1 = models.TextField(null=True, blank=True)
    c_mainaddressstreetline2 = models.TextField(null=True, blank=True)
    c_nuvalidationresult = models.TextField(null=True, blank=True)
    c_secondaryproductdiscussed = models.TextField(null=True, blank=True)
    c_district = models.TextField(null=True, blank=True)
    c_creationofchannelresponse = models.TextField(null=True, blank=True)
    c_brcurrbrand = models.TextField(null=True, blank=True)
    c_primaryproductdiscussed = models.TextField(null=True, blank=True)
    c_month = models.TextField(null=True, blank=True)
    c_sys = models.TextField(null=True, blank=True)
    c_app_num = models.TextField(null=True, blank=True)
    c_loan_id = models.TextField(null=True, blank=True)
    c_loan_account_no = models.CharField(max_length=255, null=True, blank=True)
    c_dpd_bom = models.TextField(null=True, blank=True)
    c_overdue_prin_amt = models.TextField(null=True, blank=True)
    c_overdue_int_amt = models.TextField(null=True, blank=True)
    c_overdue_lpf_amt = models.TextField(null=True, blank=True)
    c_next_cycle_due_date = models.TextField(null=True, blank=True)
    c_next_cycle_due_amount = models.TextField(null=True, blank=True)
    c_customer_mobile_num = models.TextField(null=True, blank=True)
    c_active = models.TextField(null=True, blank=True)
    c_obs_duedate = models.TextField(null=True, blank=True)
    c_obs_dueno = models.TextField(null=True, blank=True)
    c_assign_invalid_date = models.TextField(null=True, blank=True)
    c_future_prin_amt = models.TextField(null=True, blank=True)
    c_perm_full_addr = models.TextField(null=True, blank=True)
    c_perm_region = models.TextField(null=True, blank=True)
    c_perm_city = models.TextField(null=True, blank=True)
    c_perm_area = models.TextField(null=True, blank=True)
    c_curr_full_addr = models.TextField(null=True, blank=True)
    c_curr_city = models.TextField(null=True, blank=True)
    c_curr_area = models.TextField(null=True, blank=True)
    c_pos_bom = models.TextField(null=True, blank=True)
    c_pos_assign = models.TextField(null=True, blank=True)
    c_remain_prin = models.TextField(null=True, blank=True)
    c_customer_name = models.TextField(null=True, blank=True)
    c_birthday = models.TextField(null=True, blank=True)
    c_emi = models.TextField(null=True, blank=True)
    c_gender = models.TextField(null=True, blank=True)
    c_spouse_name = models.TextField(null=True, blank=True)
    c_spousephone = models.TextField(null=True, blank=True)
    c_family_phone = models.TextField(null=True, blank=True)
    c_family_book = models.TextField(null=True, blank=True)
    c_family_relation = models.TextField(null=True, blank=True)
    c_ref_name_1 = models.TextField(null=True, blank=True)
    c_ref_relationship_1 = models.TextField(null=True, blank=True)
    c_phoneref1 = models.TextField(null=True, blank=True)
    c_ref_name_2 = models.TextField(null=True, blank=True)
    c_ref_relationship_2 = models.TextField(null=True, blank=True)
    c_phoneref2 = models.TextField(null=True, blank=True)
    c_work_phone = models.TextField(null=True, blank=True)
    c_add_name_1 = models.TextField(null=True, blank=True)
    c_add_phone_1 = models.TextField(null=True, blank=True)
    c_add_phone_2 = models.TextField(null=True, blank=True)
    c_cif = models.TextField(null=True, blank=True)
    c_pernament_address = models.TextField(null=True, blank=True)
    c_domicile_address = models.TextField(null=True, blank=True)
    c_company_name = models.TextField(null=True, blank=True)
    c_tenor = models.TextField(null=True, blank=True)
    c_loan_amt = models.TextField(null=True, blank=True)
    c_disbursement_date = models.TextField(null=True, blank=True)
    c_addname2 = models.TextField(null=True, blank=True)
    c_product_kh = models.TextField(null=True, blank=True)
    c_contract_date = models.TextField(null=True, blank=True)
    c_id_card = models.TextField(null=True, blank=True)
    c_curr_account = models.TextField(null=True, blank=True)
    c_first_paid_date = models.TextField(null=True, blank=True)
    c_last_paid_date = models.TextField(null=True, blank=True)
    c_last_call_final = models.TextField(null=True, blank=True)
    c_last_result_final = models.TextField(null=True, blank=True)
    c_total_amt_paid = models.TextField(null=True, blank=True)
    c_total_overdue = models.TextField(null=True, blank=True)
    c_due_date_overdue = models.TextField(null=True, blank=True)
    c_offi_full_addr = models.TextField(null=True, blank=True)
    c_off_area = models.TextField(null=True, blank=True)
    c_off_city = models.TextField(null=True, blank=True)
    c_stk = models.TextField(null=True, blank=True)
    c_group = models.TextField(null=True, blank=True)
    c_dpd_cur = models.TextField(null=True, blank=True)
    c_dpd_assign = models.TextField(null=True, blank=True)
    c_assign_date = models.TextField(null=True, blank=True)
    c_write_off = models.TextField(null=True, blank=True)
    c_agency = models.TextField(null=True, blank=True)
    c_mob = models.TextField(null=True, blank=True)
    c_agent = models.TextField(null=True, blank=True)
    c_source = models.TextField(null=True, blank=True)
    c_last_action_time = models.TextField(null=True, blank=True)
    c_last_action_code = models.TextField(null=True, blank=True)
    c_last_remark = models.TextField(null=True, blank=True)
    c_count_connected_times = models.TextField(null=True, blank=True)
    
    class Meta:
        verbose_name = "Chien_dich_data"
        verbose_name_plural = "Chien_dich_data"
