import uuid
from django.db import models

from cnx_service.model import BaseModel


# Create your models here.
class Client(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_by = models.CharField(max_length=255, null=True, blank=True)
    created_by_name = models.CharField(max_length=255, null=True, blank=True)
    modified_by = models.CharField(max_length=255, null=True, blank=True)
    modified_by_name = models.CharField(max_length=255, null=True, blank=True)
    c_work_phone = models.TextField(null=True, blank=True)
    c_curr_full_addr = models.TextField(null=True, blank=True)
    c_call_rgrd_contact_brand_switch_reason = models.TextField(null=True, blank=True)
    c_existing_main_br_brand_name = models.TextField(null=True, blank=True)
    c_new_child_curr_brand_id = models.TextField(null=True, blank=True)
    c_overdue_prin_amt = models.TextField(null=True, blank=True)
    c_add_phone_1 = models.TextField(null=True, blank=True)
    c_add_phone_2 = models.TextField(null=True, blank=True)
    c_stt = models.TextField(null=True, blank=True)
    c_company_name = models.TextField(null=True, blank=True)
    c_perm_region = models.TextField(null=True, blank=True)
    c_status = models.TextField(null=True, blank=True)
    c_invalid_reason = models.TextField(null=True, blank=True)
    c_main_contact_home_phone = models.TextField(null=True, blank=True)
    c_call_rgrd_contact_dob = models.TextField(null=True, blank=True)
    c_order_product_code1 = models.TextField(null=True, blank=True)
    c_gender = models.TextField(null=True, blank=True)
    c_city = models.TextField(null=True, blank=True)
    c_mark_done = models.TextField(null=True, blank=True)
    c_order_product_code2 = models.TextField(null=True, blank=True)
    c_new_child_full_name = models.TextField(null=True, blank=True)
    c_md_child = models.TextField(null=True, blank=True)
    c_order_product_category1 = models.TextField(null=True, blank=True)
    c_ward = models.TextField(null=True, blank=True)
    c_order_product_category2 = models.TextField(null=True, blank=True)
    c_offi_full_addr = models.TextField(null=True, blank=True)
    c_order_product_category3 = models.TextField(null=True, blank=True)
    c_new_adult_mobile_phone = models.TextField(null=True, blank=True)
    c_new_address_street_line1 = models.TextField(null=True, blank=True)
    c_new_address_street_line2 = models.TextField(null=True, blank=True)
    c_pos_assign = models.TextField(null=True, blank=True)
    c_main_contact_other_phone = models.TextField(null=True, blank=True)
    c_tenor = models.TextField(null=True, blank=True)
    c_spouse_name = models.TextField(null=True, blank=True)
    c_call_rgrd_contact_br_brand_id = models.TextField(null=True, blank=True)
    c_brand_switch_reason = models.TextField(null=True, blank=True)
    c_br_prev_brand = models.TextField(null=True, blank=True)
    c_call_status = models.TextField(null=True, blank=True)
    c_main_contact_first_name = models.TextField(null=True, blank=True)
    c_st = models.TextField(null=True, blank=True)
    c_product = models.TextField(null=True, blank=True)
    c_new_address_city = models.TextField(null=True, blank=True)
    c_new_adult_full_name = models.TextField(null=True, blank=True)
    c_overdue_lpf_amt = models.TextField(null=True, blank=True)
    c_CoNH = models.TextField(null=True, blank=True)
    c_loan_amt = models.TextField(null=True, blank=True)
    c_perm_full_addr = models.TextField(null=True, blank=True)
    c_new_child_first_name = models.TextField(null=True, blank=True)
    c_spousephone = models.TextField(null=True, blank=True)
    c_loan_account_no = models.CharField(max_length=255, unique=True, null=True, blank=True, db_index=True)
    c_create_new_adult = models.TextField(null=True, blank=True)
    c_call_outcome = models.TextField(null=True, blank=True)
    c_successful_reason = models.TextField(null=True, blank=True)
    c_customer_name = models.TextField(null=True, blank=True)
    c_last_paid_date = models.TextField(null=True, blank=True)
    c_curr_city = models.TextField(null=True, blank=True)
    c_agent = models.TextField(null=True, blank=True)
    c_subject = models.TextField(null=True, blank=True)
    c_overdue_int_amt = models.TextField(null=True, blank=True)
    c_source = models.TextField(null=True, blank=True)
    
    class Meta:
        verbose_name = "Client"
        verbose_name_plural = "Clients"

