import uuid
from django.db import models

from cnx_service.model import BaseModel

class HistoryCallVB(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    createdBy = models.CharField(max_length=255, null=True, blank=True)
    createdByName = models.CharField(max_length=255, null=True, blank=True)
    modifiedBy = models.CharField(max_length=255, null=True, blank=True)
    modifiedByName = models.CharField(max_length=255, null=True, blank=True)
    c_Overdue_PRIN_Amt = models.TextField(null=True, blank=True)
    c_MONTH = models.TextField(null=True, blank=True)
    c_LAST_CALL_FINAL = models.TextField(null=True, blank=True)
    c_OBS_DueDate = models.TextField(null=True, blank=True)
    c_REF_NAME_1 = models.TextField(null=True, blank=True)
    c_REF_NAME_2 = models.TextField(null=True, blank=True)
    c_CURR_FULL_ADDR = models.TextField(null=True, blank=True)
    c_STK = models.TextField(null=True, blank=True)
    c_DPD_BOM = models.TextField(null=True, blank=True)
    c_DISBURSEMENT_DATE = models.TextField(null=True, blank=True)
    c_DPD_CUR = models.TextField(null=True, blank=True)
    c_Next_Cycle_Due_Amount = models.TextField(null=True, blank=True)
    c_PRODUCT = models.TextField(null=True, blank=True)
    c_PERM_REGION = models.TextField(null=True, blank=True)
    c_PERMANENT_ADDRESS = models.TextField(null=True, blank=True)
    c_WRITE_OFF = models.TextField(null=True, blank=True)
    c_ADD_NAME_2 = models.TextField(null=True, blank=True)
    c_BIRTHDAY = models.TextField(null=True, blank=True)
    c_ADD_NAME_1 = models.TextField(null=True, blank=True)
    c_LOAN_AMT = models.TextField(null=True, blank=True)
    c_DPD_ASSIGN = models.TextField(null=True, blank=True)
    c_EMI = models.TextField(null=True, blank=True)
    c_OFFI_CITY = models.TextField(null=True, blank=True)
    c_Status = models.TextField(null=True, blank=True)
    c_CIF = models.TextField(null=True, blank=True)
    c_Assign_Invalid_Date = models.TextField(null=True, blank=True)
    c_LOANID = models.TextField(null=True, blank=True)
    c_SYS = models.TextField(null=True, blank=True)
    c_LAST_RESULT_FINAL = models.TextField(null=True, blank=True)
    c_CURRENT_ACCOUNT = models.TextField(null=True, blank=True)
    c_SPOUSEPHONE = models.TextField(null=True, blank=True)
    c_COMPANY_NAME = models.TextField(null=True, blank=True)
    c_Active = models.TextField(null=True, blank=True)
    c_Next_Cycle_DueDate = models.TextField(null=True, blank=True)
    c_DOMICILE_ADDRESS = models.TextField(null=True, blank=True)
    c_Overdue_INT_Amt = models.TextField(null=True, blank=True)
    c_FUTURE_PRIN_AMT = models.TextField(null=True, blank=True)
    c_FAMILY_RELATION = models.TextField(null=True, blank=True)
    c_PHONEREF1 = models.TextField(null=True, blank=True)
    c_PHONEREF2 = models.TextField(null=True, blank=True)
    c_ID_CARD = models.TextField(null=True, blank=True)
    c_REF_RELATIONSHIP_2 = models.TextField(null=True, blank=True)
    c_CUSTOMER_MOBILE_NUM = models.TextField(null=True, blank=True)
    c_FAMILYBOOK = models.TextField(null=True, blank=True)
    c_REF_RELATIONSHIP_1 = models.TextField(null=True, blank=True)
    c_LAST_PAID_DATE = models.TextField(null=True, blank=True)
    c_OFFI_AREA = models.TextField(null=True, blank=True)
    c_TOTAL_OVERDUE = models.TextField(null=True, blank=True)
    c_PERM_CITY = models.TextField(null=True, blank=True)
    c_CURR_AREA = models.TextField(null=True, blank=True)
    c_LOAN_Account_No = models.TextField(null=True, blank=True)
    c_SPOUSE_NAME = models.TextField(null=True, blank=True)
    c_AGENT = models.TextField(null=True, blank=True)
    c_OFFI_FULL_ADDR = models.TextField(null=True, blank=True)
    c_GROUP = models.TextField(null=True, blank=True)
    c_Application_Number = models.TextField(null=True, blank=True)
    c_CONTRACT_DATE = models.TextField(null=True, blank=True)
    c_TOTAL_AMT_PAID = models.TextField(null=True, blank=True)
    c_GENDER = models.TextField(null=True, blank=True)
    c_ADD_PHONE_2 = models.TextField(null=True, blank=True)
    c_ADD_PHONE_1 = models.TextField(null=True, blank=True)
    c_TENOR = models.TextField(null=True, blank=True)
    c_DUE_DATE_OVERDUE = models.TextField(null=True, blank=True)
    c_MOB = models.TextField(null=True, blank=True)
    c_FIRST_PAID_DATE = models.TextField(null=True, blank=True)
    c_POS_BOM = models.TextField(null=True, blank=True)
    c_CURR_CITY = models.TextField(null=True, blank=True)
    c_ASSIGN_DATE = models.TextField(null=True, blank=True)
    c_PERM_AREA = models.TextField(null=True, blank=True)
    c_WORK_PHONE = models.TextField(null=True, blank=True)
    c_AGENCY = models.TextField(null=True, blank=True)
    c_OBS_DueNo = models.TextField(null=True, blank=True)
    c_CUSTOMER_NAME = models.TextField(null=True, blank=True)
    c_REMAIN_PRIN = models.TextField(null=True, blank=True)
    c_Overdue_LPF_Amt = models.TextField(null=True, blank=True)
    c_FAMILY_PHONE = models.TextField(null=True, blank=True)
    c_PERM_FULL_ADDR = models.TextField(null=True, blank=True)
    c_POS_ASSIGN = models.TextField(null=True, blank=True)
    c_fkChienDich = models.CharField(max_length=255, null=True, blank=True)
    c_ten_chiendich = models.TextField(null=True, blank=True)
    c_id_call = models.CharField(max_length=255)
    c_stt_dsgoi = models.TextField(null=True, blank=True)
    c_phone_call = models.TextField(null=True, blank=True)
    c_start_time = models.TextField(null=True, blank=True)
    c_end_time = models.TextField(null=True, blank=True)
    c_ans_time = models.TextField(null=True, blank=True)
    c_trangthai = models.TextField(null=True, blank=True)
    c_trangthai_view = models.TextField(null=True, blank=True)
    c_Playback = models.TextField(null=True, blank=True)
    c_file = models.TextField(null=True, blank=True)
    c_contenkey = models.TextField(null=True, blank=True)
    c_duration = models.TextField(null=True, blank=True)
    
    class Meta:
        verbose_name = "HistoryCallVB"
        verbose_name_plural = "HistoryCallVBs"