import uuid
from django.db import models

from cnx_service.model import BaseModel

class HistoryCall(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    createdBy = models.CharField(max_length=255, null=True, blank=True)
    createdByName = models.CharField(max_length=255, null=True, blank=True)
    modifiedBy = models.CharField(max_length=255, null=True, blank=True)
    modifiedByName = models.CharField(max_length=255, null=True, blank=True)
    c_recording_url = models.TextField(null=True, blank=True)
    c_dir = models.TextField(null=True, blank=True)
    c_call_cost = models.TextField(null=True, blank=True)
    c_sdthienthi = models.TextField(null=True, blank=True)
    c_destination_type = models.TextField(null=True, blank=True)
    c_in_queue_frist = models.TextField(null=True, blank=True)
    c_talking_duration = models.TextField(null=True, blank=True)
    c_survey_stt = models.TextField(null=True, blank=True)
    c_total_dur = models.TextField(null=True, blank=True)
    c_To = models.TextField(null=True, blank=True)
    c_action_dn_type = models.TextField(null=True, blank=True)
    c_source_caller_id = models.TextField(null=True, blank=True)
    c_destination_caller_id = models.TextField(null=True, blank=True)
    c_ThoiLuong = models.TextField(null=True, blank=True)
    c_StartTime = models.TextField(null=True, blank=True)
    c_source_type = models.TextField(null=True, blank=True)
    c_source_display_name = models.TextField(null=True, blank=True)
    c_trunk = models.TextField(null=True, blank=True)
    c_call_id = models.CharField(max_length=255, null=True, blank=True)
    c_sip_log = models.TextField(null=True, blank=True)
    c_destination_dn = models.TextField(null=True, blank=True)
    c_start_time = models.CharField(max_length=30, null=True, blank=True)
    c_s_start_time = models.DateTimeField(null=True, blank=True)
    c_subrow_desc_number = models.TextField(null=True, blank=True)
    c_makhachhang = models.TextField(null=True, blank=True)
    c_so_ext = models.TextField(null=True, blank=True)
    c_status_log = models.TextField(null=True, blank=True)
    c_action_dn_display_name = models.TextField(null=True, blank=True)
    c_is_answered = models.TextField(null=True, blank=True)
    c_TrangThaiCuocGoi = models.TextField(null=True, blank=True)
    c_s_end_time = models.TextField(null=True, blank=True)
    c_indent = models.TextField(null=True, blank=True)
    c_action_type = models.TextField(null=True, blank=True)
    c_CallType = models.TextField(null=True, blank=True)
    c_note_end = models.TextField(null=True, blank=True)
    c_ringing_duration = models.TextField(null=True, blank=True)
    c_talktime_cost = models.TextField(null=True, blank=True)
    c_tongdai = models.TextField(null=True, blank=True)
    c_answered = models.TextField(null=True, blank=True)
    c_in_queue_time = models.TextField(null=True, blank=True)
    c_source_dn = models.TextField(null=True, blank=True)
    c_From = models.TextField(null=True, blank=True)
    c_action_dn_dn = models.TextField(null=True, blank=True)
    c_KetThucBoi = models.TextField(null=True, blank=True)
    c_queue_name = models.TextField(null=True, blank=True)
    c_destination_display_name = models.TextField(null=True, blank=True)
    c_action_dn_caller_id = models.TextField(null=True, blank=True)
    c_Recording = models.TextField(null=True, blank=True)
    c_user_name_survey = models.TextField(null=True, blank=True)
    c_action_code = models.TextField(null=True, blank=True)
    c_dir_code = models.TextField(null=True, blank=True)
    c_account_no = models.TextField(null=True, blank=True)
    c_in_talking = models.TextField(null=True, blank=True)
    c_in_agent_ans = models.TextField(null=True, blank=True)
    c_idcd_hienthi = models.TextField(null=True, blank=True)
    c_fk_id_tk = models.TextField(null=True, blank=True)
    c_loai_cd = models.TextField(null=True, blank=True)
    c_status_log_code = models.TextField(null=True, blank=True)
    c_time_customer_ans = models.TextField(null=True, blank=True)
    c_time_markdone = models.TextField(null=True, blank=True)
    c_hienthi = models.CharField(max_length=5, null=True, blank=True)
    c_dir_text = models.TextField(null=True, blank=True)
    c_time_agent_ans = models.TextField(null=True, blank=True)
    c_terminatedby = models.TextField(null=True, blank=True)
    c_fk_idKH = models.CharField(max_length=255, null=True, blank=True)
    c_waiting_queue = models.TextField(null=True, blank=True)
    c_status_log_text = models.TextField(null=True, blank=True)
    c_callStatus = models.TextField(null=True, blank=True)
    c_terminated = models.TextField(null=True, blank=True)
    c_stt_dsgoi = models.TextField(null=True, blank=True)
    c_auto_recording = models.TextField(null=True, blank=True)
    c_total_dur_survey = models.TextField(null=True, blank=True)
    c_callOutcome = models.TextField(null=True, blank=True)
    c_callOutcome_sub = models.TextField(null=True, blank=True)
    c_ten_cd = models.TextField(null=True, blank=True)
    c_call_id_markdone = models.TextField(null=True, blank=True)
    c_queue_auto_number = models.TextField(null=True, blank=True)
    c_in_ivr_frist = models.TextField(null=True, blank=True)
    c_cost = models.TextField(null=True, blank=True)
    c_in_ivr_dur = models.TextField(null=True, blank=True)
    c_type = models.TextField(null=True, blank=True)
    c_fkidivr = models.TextField(null=True, blank=True)
    c_fkTicket = models.TextField(null=True, blank=True)
    c_status_logsip = models.TextField(null=True, blank=True)
    c_nhanhIVR = models.TextField(null=True, blank=True)
    c_fkKH = models.TextField(null=True, blank=True)
    c_status_autocall = models.TextField(null=True, blank=True)
    c_type_cost = models.TextField(null=True, blank=True)
    c_cost_minutes_inbound = models.TextField(null=True, blank=True)
    c_autocall_sttdsgoi = models.TextField(null=True, blank=True)
    c_maplog_outbound = models.TextField(null=True, blank=True)
    c_auto_waiting = models.TextField(null=True, blank=True)
    c_autocall_soqueue = models.TextField(null=True, blank=True)
    c_auto_agent_ans = models.TextField(null=True, blank=True)
    c_auto_talking = models.TextField(null=True, blank=True)
    c_auto_url_recording = models.TextField(null=True, blank=True)
    c_auto_ext_call = models.TextField(null=True, blank=True)
    c_auto_ringingkh = models.TextField(null=True, blank=True)
    c_type_str = models.TextField(null=True, blank=True)
    c_url_recording_vm = models.TextField(null=True, blank=True)
    c_id_vm = models.TextField(null=True, blank=True)
    c_fkid_callback = models.TextField(null=True, blank=True)
    c_phongban = models.TextField(null=True, blank=True)
    
    class Meta:
        verbose_name = "HistoryCall"
        verbose_name_plural = "HistoryCalls"

