name: Deploy to Server

on:
  push:
    branches:
      - main  # Runs only when code is pushed to main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Docker Image
        run: docker build -t your-dockerhub-username/your-image-name:latest .

      - name: Push Docker Image to DockerHub
        run: docker push your-dockerhub-username/your-image-name:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull your-dockerhub-username/your-image-name:latest
            docker stop app-container || true
            docker rm app-container || true
            docker run -d --name app-container -p 80:80 your-dockerhub-username/your-image-name:latest
