name: Deploy to Server

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
  push:
    branches: [ "main" ]

jobs:
  deploy_if_merged:
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted
    environment: dev

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v2

    - name: Stop and Remove Old Containers
      run: |
        docker-compose -f staging.yml down || true

    - name: Build and Start Containers
      run: |
        docker-compose -f staging.yml up --build -d
