name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 1: Verify server connectivity with Ping
    - name: Check if server is reachable
      run: |
        if ping -c 4 ${{ secrets.SSH_HOST }}; then
          echo "✅ Server is reachable"
        else
          echo "❌ Server is unreachable"
          exit 1
        fi

    # Step 2: Check if SSH Port (Default 22) is Open
    - name: Check if SSH port is open
      run: |
        if nc -zv ${{ secrets.SSH_HOST }} 22; then
          echo "✅ Port 22 is open"
        else
          echo "❌ Port 22 is closed"
          exit 1
        fi

    - name: Debug SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo ✅ SSH Connection Successful!"


    # Step 4: Deploy to Server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        echo "🚀 Starting Deployment..."
        cd /home/devadmin/cnx  # Change this to your actual project path
        echo "🔄 Pulling latest code..."
        git pull origin main || { echo "❌ Git pull failed"; exit 1; }
        
        echo "🔄 Restarting Docker services..."
        docker compose down || { echo "❌ Docker down failed"; exit 1; }
        docker compose up -d --build || { echo "❌ Docker build failed"; exit 1; }
        
        echo "✅ Deployment successful!"
        exit
        EOF
