name: Pre-commit CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Run pre-commit hooks
        run: |
          docker run --rm myapp:latest pre-commit run --all-files --show-diff-on-failure || (echo "❌ Pre-commit failed! Run 'pre-commit run --all-files' locally to fix." && exit 1)

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure || (echo "❌ Pre-commit failed! Run 'pre-commit run --all-files' locally to fix." && exit 1)

      - name: Run Django tests
        run: |
          docker run --rm myapp:latest python manage.py test