name: Pre-commit CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
        
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc build-essential default-libmysqlclient-dev pkg-config

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure || (echo "❌ Pre-commit failed! Run 'pre-commit run --all-files' locally to fix." && exit 1)

      - name: Run Django tests
        run: python manage.py test
